name: Run Tests

on:
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * *'

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: ee-test
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            matrix:
                php: [7.1]
                os: [ubuntu-latest]

        name: P${{ matrix.php }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Copy config.php
              run: php -r "file_exists('system/user/config/config.php') || copy('tests/docker/config.php', 'system/user/config/config.php');"

            - name: Setup Ruby
              uses: actions/setup-ruby@v1
              with:
                ruby-version: '2.4'

            - name: Install Ruby dependencies
              run: |
                sudo apt-get update
                sudo apt-get -yqq install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x libmysqlclient-dev
                gem install bundler
                bundle install --no-deployment --gemfile=tests/rspec/Gemfile --path=~/gems/

            - name: Start webserver
              run: sudo php -S localhost:8080 &

            - name: Configure MySQL
              run: mysql -u root -proot -e 'SET GLOBAL sql_mode="ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";'

            - name: Run RSpec tests
              working-directory: tests/rspec
              run: bundle exec rspec -c -fd -fh tests/**/*.rb
